[build]
  publish = "public"
  command = "echo SITE_RECAPTCHA_KEY=$SITE_RECAPTCHA_KEY >> .env.production && gatsby build"
[build.environment]
  NODE_VERSION = "11.7.0"
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--pure-lockfile --verbose --no-ignore-optional"